### PR TITLE
todoapp: update gitignore to reflect new post-init state

### PR DESCRIPTION
**Pull request by bpo**
The first step of the tutorial is `dagger init`, which leaves the git index in a
dirty state because of [recent changes to gitignore](https://github.com/dagger/dagger/pull/1146).

This update just copies the newer generated gitignore

### CODE REVIEW

**Comment by gerhard** [comment]
This is a great first contribution @bpo, thank you!

Would you mind signing the commit? [This is how you can do that](https://github.com/dagger/examples/pull/47/checks?check_run_id=4754503346).

**Comment by bpo** [comment]
Ah - sorry for the noise! If you add [CONTRIBUTING.md](https://github.com/dagger/dagger/blob/main/CONTRIBUTING.md) to a `.github` repository [it will show up for all repositories in the org](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file). Should help reduce distractions from drive-bys like me. Cheers!

**Comment by gerhard** [comment]
> Ah - sorry for the noise! If you add [CONTRIBUTING.md](https://github.com/dagger/dagger/blob/main/CONTRIBUTING.md) to a `.github` repository [it will show up for all repositories in the org](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file).

That is a nice trick which I didn't know about! [I just did](https://github.com/dagger/.github/blob/main/CONTRIBUTING.md) but there is no `CONTRIBUTING.md` link showing on this repository: https://github.com/dagger/examples

Any ideas as to what I might have done wrong?

**Comment by bpo** [comment]
> Any ideas as to what I might have done wrong?

It doesn't show up in the file listing but a link to it appears in the UI when people open issues, pull requests, etc. Looks good to me, you should be all set.

**Comment by gerhard** [comment]
When I open a new issue in this repo, I can see now the tooltip with the contributing guidelines link.
That's exactly what we wanted, thank you!

image

**Pull request closed without merging**
